[2023-06-28T09:25:40.125+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=scheduled__2023-06-28T09:24:00+00:00/task_id=snowflake_sensor_task permission to 509
[2023-06-28T09:25:40.127+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=scheduled__2023-06-28T09:24:00+00:00/task_id=snowflake_sensor_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=scheduled__2023-06-28T09:24:00+00:00/task_id=snowflake_sensor_task'
[2023-06-28T09:25:40.168+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=scheduled__2023-06-28T09:24:00+00:00/task_id=snowflake_sensor_task permission to 509
[2023-06-28T09:25:40.169+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=scheduled__2023-06-28T09:24:00+00:00/task_id=snowflake_sensor_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=scheduled__2023-06-28T09:24:00+00:00/task_id=snowflake_sensor_task'
[2023-06-28T09:25:40.216+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Loop.snowflake_sensor_task scheduled__2023-06-28T09:24:00+00:00 [queued]>
[2023-06-28T09:25:40.234+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Loop.snowflake_sensor_task scheduled__2023-06-28T09:24:00+00:00 [queued]>
[2023-06-28T09:25:40.235+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-28T09:25:40.256+0000] {taskinstance.py:1327} INFO - Executing <Task(SnowflakeStreamSensor): snowflake_sensor_task> on 2023-06-28 09:24:00+00:00
[2023-06-28T09:25:40.264+0000] {standard_task_runner.py:57} INFO - Started process 1239 to run task
[2023-06-28T09:25:40.269+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2_Test_Badge_5_Loop', 'snowflake_sensor_task', 'scheduled__2023-06-28T09:24:00+00:00', '--job-id', '440', '--raw', '--subdir', 'DAGS_FOLDER/test_loop.py', '--cfg-path', '/tmp/tmp16p9gepd']
[2023-06-28T09:25:40.270+0000] {standard_task_runner.py:85} INFO - Job 440: Subtask snowflake_sensor_task
[2023-06-28T09:25:40.341+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=scheduled__2023-06-28T09:24:00+00:00/task_id=snowflake_sensor_task permission to 509
[2023-06-28T09:25:40.342+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=scheduled__2023-06-28T09:24:00+00:00/task_id=snowflake_sensor_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Loop/run_id=scheduled__2023-06-28T09:24:00+00:00/task_id=snowflake_sensor_task'
[2023-06-28T09:25:40.345+0000] {task_command.py:410} INFO - Running <TaskInstance: 2_Test_Badge_5_Loop.snowflake_sensor_task scheduled__2023-06-28T09:24:00+00:00 [running]> on host a3cd9226e3f8
[2023-06-28T09:25:40.468+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2_Test_Badge_5_Loop' AIRFLOW_CTX_TASK_ID='snowflake_sensor_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-28T09:24:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-28T09:24:00+00:00'
[2023-06-28T09:25:40.470+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1188, in execute
    raise NotImplementedError()
NotImplementedError
[2023-06-28T09:25:40.482+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=2_Test_Badge_5_Loop, task_id=snowflake_sensor_task, execution_date=20230628T092400, start_date=20230628T092540, end_date=20230628T092540
[2023-06-28T09:25:40.500+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 440 for task snowflake_sensor_task (; 1239)
[2023-06-28T09:25:40.565+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-28T09:25:40.606+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
