[2023-06-27T14:59:12.992+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_ed_enhanced permission to 509
[2023-06-27T14:59:12.993+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_ed_enhanced permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_ed_enhanced'
[2023-06-27T14:59:13.019+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_ed_enhanced permission to 509
[2023-06-27T14:59:13.020+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_ed_enhanced permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_ed_enhanced'
[2023-06-27T14:59:13.171+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.create_ed_enhanced manual__2023-06-27T14:58:09.616240+00:00 [queued]>
[2023-06-27T14:59:13.181+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.create_ed_enhanced manual__2023-06-27T14:58:09.616240+00:00 [queued]>
[2023-06-27T14:59:13.182+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-27T14:59:13.200+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_ed_enhanced> on 2023-06-27 14:58:09.616240+00:00
[2023-06-27T14:59:13.206+0000] {standard_task_runner.py:57} INFO - Started process 8233 to run task
[2023-06-27T14:59:13.210+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2_Test_Badge_5_Setup', 'create_ed_enhanced', 'manual__2023-06-27T14:58:09.616240+00:00', '--job-id', '372', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp6ewe2lax']
[2023-06-27T14:59:13.212+0000] {standard_task_runner.py:85} INFO - Job 372: Subtask create_ed_enhanced
[2023-06-27T14:59:13.254+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_ed_enhanced permission to 509
[2023-06-27T14:59:13.255+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_ed_enhanced permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:58:09.616240+00:00/task_id=create_ed_enhanced'
[2023-06-27T14:59:13.257+0000] {task_command.py:410} INFO - Running <TaskInstance: 2_Test_Badge_5_Setup.create_ed_enhanced manual__2023-06-27T14:58:09.616240+00:00 [running]> on host eb22b15bae36
[2023-06-27T14:59:13.370+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2_Test_Badge_5_Setup' AIRFLOW_CTX_TASK_ID='create_ed_enhanced' AIRFLOW_CTX_EXECUTION_DATE='2023-06-27T14:58:09.616240+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-27T14:58:09.616240+00:00'
[2023-06-27T14:59:13.373+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-27T14:59:13.374+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt && dbt run --model ed_enhanced']
[2023-06-27T14:59:13.384+0000] {subprocess.py:86} INFO - Output:
[2023-06-27T14:59:16.689+0000] {subprocess.py:93} INFO - [0m14:59:16  Running with dbt=1.5.1
[2023-06-27T14:59:23.336+0000] {subprocess.py:93} INFO - [0m14:59:23  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-06-27T14:59:23.337+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2023-06-27T14:59:23.337+0000] {subprocess.py:93} INFO - - models.badge_5.time_of_day_lu
[2023-06-27T14:59:23.423+0000] {subprocess.py:93} INFO - [0m14:59:23  Found 3 models, 0 tests, 0 snapshots, 0 analyses, 456 macros, 0 operations, 1 seed file, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-27T14:59:23.427+0000] {subprocess.py:93} INFO - [0m14:59:23  The selection criterion 'ed_enhanced' does not match any nodes
[2023-06-27T14:59:23.429+0000] {subprocess.py:93} INFO - [0m14:59:23
[2023-06-27T14:59:23.431+0000] {subprocess.py:93} INFO - [0m14:59:23  Nothing to do. Try checking your model configs and model specification args
[2023-06-27T14:59:24.182+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-27T14:59:24.213+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=2_Test_Badge_5_Setup, task_id=create_ed_enhanced, execution_date=20230627T145809, start_date=20230627T145913, end_date=20230627T145924
[2023-06-27T14:59:24.257+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-27T14:59:24.281+0000] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
