[2023-06-27T11:35:39.100+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T11:34:27.337092+00:00/task_id=trigger_dag permission to 509
[2023-06-27T11:35:39.101+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T11:34:27.337092+00:00/task_id=trigger_dag permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T11:34:27.337092+00:00/task_id=trigger_dag'
[2023-06-27T11:35:39.137+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T11:34:27.337092+00:00/task_id=trigger_dag permission to 509
[2023-06-27T11:35:39.138+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T11:34:27.337092+00:00/task_id=trigger_dag permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T11:34:27.337092+00:00/task_id=trigger_dag'
[2023-06-27T11:35:39.333+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.trigger_dag manual__2023-06-27T11:34:27.337092+00:00 [queued]>
[2023-06-27T11:35:39.345+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.trigger_dag manual__2023-06-27T11:34:27.337092+00:00 [queued]>
[2023-06-27T11:35:39.346+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-27T11:35:39.365+0000] {taskinstance.py:1327} INFO - Executing <Task(TriggerDagRunOperator): trigger_dag> on 2023-06-27 11:34:27.337092+00:00
[2023-06-27T11:35:39.371+0000] {standard_task_runner.py:57} INFO - Started process 740 to run task
[2023-06-27T11:35:39.376+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2_Test_Badge_5_Setup', 'trigger_dag', 'manual__2023-06-27T11:34:27.337092+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpydll5e9w']
[2023-06-27T11:35:39.378+0000] {standard_task_runner.py:85} INFO - Job 269: Subtask trigger_dag
[2023-06-27T11:35:39.434+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T11:34:27.337092+00:00/task_id=trigger_dag permission to 509
[2023-06-27T11:35:39.435+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T11:34:27.337092+00:00/task_id=trigger_dag permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T11:34:27.337092+00:00/task_id=trigger_dag'
[2023-06-27T11:35:39.438+0000] {task_command.py:410} INFO - Running <TaskInstance: 2_Test_Badge_5_Setup.trigger_dag manual__2023-06-27T11:34:27.337092+00:00 [running]> on host 117903831da4
[2023-06-27T11:35:39.498+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-27T11:35:39.546+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2_Test_Badge_5_Setup' AIRFLOW_CTX_TASK_ID='trigger_dag' AIRFLOW_CTX_EXECUTION_DATE='2023-06-27T11:34:27.337092+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-27T11:34:27.337092+00:00'
[2023-06-27T11:35:39.655+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=2_Test_Badge_5_Setup, task_id=trigger_dag, execution_date=20230627T113427, start_date=20230627T113539, end_date=20230627T113539
[2023-06-27T11:35:39.683+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-27T11:35:39.702+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
