[2023-06-27T14:55:23.598+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:54:13.718499+00:00/task_id=create_ed_enhanced permission to 509
[2023-06-27T14:55:23.599+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:54:13.718499+00:00/task_id=create_ed_enhanced permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:54:13.718499+00:00/task_id=create_ed_enhanced'
[2023-06-27T14:55:23.631+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:54:13.718499+00:00/task_id=create_ed_enhanced permission to 509
[2023-06-27T14:55:23.632+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:54:13.718499+00:00/task_id=create_ed_enhanced permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:54:13.718499+00:00/task_id=create_ed_enhanced'
[2023-06-27T14:55:23.809+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.create_ed_enhanced manual__2023-06-27T14:54:13.718499+00:00 [queued]>
[2023-06-27T14:55:23.818+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.create_ed_enhanced manual__2023-06-27T14:54:13.718499+00:00 [queued]>
[2023-06-27T14:55:23.819+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-27T14:55:23.835+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): create_ed_enhanced> on 2023-06-27 14:54:13.718499+00:00
[2023-06-27T14:55:23.841+0000] {standard_task_runner.py:57} INFO - Started process 6591 to run task
[2023-06-27T14:55:23.845+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2_Test_Badge_5_Setup', 'create_ed_enhanced', 'manual__2023-06-27T14:54:13.718499+00:00', '--job-id', '351', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpygasksvi']
[2023-06-27T14:55:23.847+0000] {standard_task_runner.py:85} INFO - Job 351: Subtask create_ed_enhanced
[2023-06-27T14:55:23.894+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:54:13.718499+00:00/task_id=create_ed_enhanced permission to 509
[2023-06-27T14:55:23.895+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:54:13.718499+00:00/task_id=create_ed_enhanced permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T14:54:13.718499+00:00/task_id=create_ed_enhanced'
[2023-06-27T14:55:23.898+0000] {task_command.py:410} INFO - Running <TaskInstance: 2_Test_Badge_5_Setup.create_ed_enhanced manual__2023-06-27T14:54:13.718499+00:00 [running]> on host eb22b15bae36
[2023-06-27T14:55:24.036+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2_Test_Badge_5_Setup' AIRFLOW_CTX_TASK_ID='create_ed_enhanced' AIRFLOW_CTX_EXECUTION_DATE='2023-06-27T14:54:13.718499+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-27T14:54:13.718499+00:00'
[2023-06-27T14:55:24.039+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-27T14:55:24.040+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /dbt && dbt run --model ed_enhanced']
[2023-06-27T14:55:24.053+0000] {subprocess.py:86} INFO - Output:
[2023-06-27T14:55:26.950+0000] {subprocess.py:93} INFO - [0m14:55:26  Running with dbt=1.5.1
[2023-06-27T14:55:34.271+0000] {subprocess.py:93} INFO - [0m14:55:34  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-06-27T14:55:34.272+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2023-06-27T14:55:34.272+0000] {subprocess.py:93} INFO - - models.badge_5.time_of_day_lu
[2023-06-27T14:55:34.326+0000] {subprocess.py:93} INFO - [0m14:55:34  Found 3 models, 0 tests, 0 snapshots, 0 analyses, 456 macros, 0 operations, 1 seed file, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-27T14:55:34.329+0000] {subprocess.py:93} INFO - [0m14:55:34  The selection criterion 'ed_enhanced' does not match any nodes
[2023-06-27T14:55:34.330+0000] {subprocess.py:93} INFO - [0m14:55:34
[2023-06-27T14:55:34.332+0000] {subprocess.py:93} INFO - [0m14:55:34  Nothing to do. Try checking your model configs and model specification args
[2023-06-27T14:55:35.005+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-27T14:55:35.042+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=2_Test_Badge_5_Setup, task_id=create_ed_enhanced, execution_date=20230627T145413, start_date=20230627T145523, end_date=20230627T145535
[2023-06-27T14:55:35.086+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-27T14:55:35.111+0000] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
