[2023-06-27T15:05:24.725+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T15:04:05.719299+00:00/task_id=trigger_dag permission to 509
[2023-06-27T15:05:24.726+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T15:04:05.719299+00:00/task_id=trigger_dag permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T15:04:05.719299+00:00/task_id=trigger_dag'
[2023-06-27T15:05:24.764+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T15:04:05.719299+00:00/task_id=trigger_dag permission to 509
[2023-06-27T15:05:24.765+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T15:04:05.719299+00:00/task_id=trigger_dag permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T15:04:05.719299+00:00/task_id=trigger_dag'
[2023-06-27T15:05:24.948+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.trigger_dag manual__2023-06-27T15:04:05.719299+00:00 [queued]>
[2023-06-27T15:05:24.960+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 2_Test_Badge_5_Setup.trigger_dag manual__2023-06-27T15:04:05.719299+00:00 [queued]>
[2023-06-27T15:05:24.961+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-27T15:05:24.981+0000] {taskinstance.py:1327} INFO - Executing <Task(TriggerDagRunOperator): trigger_dag> on 2023-06-27 15:04:05.719299+00:00
[2023-06-27T15:05:24.987+0000] {standard_task_runner.py:57} INFO - Started process 1652 to run task
[2023-06-27T15:05:24.993+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '2_Test_Badge_5_Setup', 'trigger_dag', 'manual__2023-06-27T15:04:05.719299+00:00', '--job-id', '404', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp6_iv9l8s']
[2023-06-27T15:05:24.996+0000] {standard_task_runner.py:85} INFO - Job 404: Subtask trigger_dag
[2023-06-27T15:05:25.050+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T15:04:05.719299+00:00/task_id=trigger_dag permission to 509
[2023-06-27T15:05:25.051+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T15:04:05.719299+00:00/task_id=trigger_dag permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=2_Test_Badge_5_Setup/run_id=manual__2023-06-27T15:04:05.719299+00:00/task_id=trigger_dag'
[2023-06-27T15:05:25.055+0000] {task_command.py:410} INFO - Running <TaskInstance: 2_Test_Badge_5_Setup.trigger_dag manual__2023-06-27T15:04:05.719299+00:00 [running]> on host 065d269f5e6c
[2023-06-27T15:05:25.115+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-06-27T15:05:25.166+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='2_Test_Badge_5_Setup' AIRFLOW_CTX_TASK_ID='trigger_dag' AIRFLOW_CTX_EXECUTION_DATE='2023-06-27T15:04:05.719299+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-27T15:04:05.719299+00:00'
[2023-06-27T15:05:25.270+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=2_Test_Badge_5_Setup, task_id=trigger_dag, execution_date=20230627T150405, start_date=20230627T150524, end_date=20230627T150525
[2023-06-27T15:05:25.324+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-27T15:05:25.344+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
